T5332: Fix show policy route without attahed interface
Interface may not be present in the op-mode dictionary, it cause
KeyError: 'interface' for policy route