syslog: T2778: fix invalid handling of logrotate and default values
There was no /var/log/messages handler for logrotate making rsyslog
crash after a few days.

In addition we had some JIna2 templating errors for hosts, user and file
CLI nodes

jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'facility'

Looks like therey are used rarely ;) - lucky me!