firewall: T1461: deleting 'firewall options' causes Python TypeError
[ firewall options interface wg01 ]
Traceback (most recent call last):
  File "/usr/libexec/vyos/conf_mode/firewall_options.py", line 139, in <module>
    apply(c)
  File "/usr/libexec/vyos/conf_mode/firewall_options.py", line 97, in apply
    if tcp['new_chain4']:
TypeError: 'NoneType' object is not subscriptable

delete [ firewall options ] failed
delete [ firewall ] failed
Commit failed

(cherry picked from commit efb1a1c88f436a3704c4ca6e15b65aeded4b9654)