ifconfig: vxlan: T2629: append() takes exactly one argument
Commit 9390988709 ("vxlan: T2629: fix multiple configuration issues") called
append() on a list and passed two arguments which is invalid.

Traceback (most recent call last):
  File "/usr/libexec/vyos/conf_mode/interfaces-vxlan.py", line 300, in <module>
    apply(c)
  File "/usr/libexec/vyos/conf_mode/interfaces-vxlan.py", line 245, in apply
    v = VXLANIf(vxlan['intf'], **conf)
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/interface.py", line 221, in __init__
    self._create()
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/vxlan.py", line 84, in _create
    cmdline.append('group', 'src_interface')
TypeError: append() takes exactly one argument (2 given)