[bridge] T1156: add missing if statement in config-migration
Fixes:
Traceback (most recent call last):
  File "/opt/vyatta/etc/config-migrate/migrate/interfaces/0-to-1", line 27, in <module>
    for br in config.list_nodes(base):
  File "/usr/lib/python3/dist-packages/vyos/configtree.py", line 255, in list_nodes
    raise ConfigTreeError("Path [{}] doesn't exist".format(path_str))
vyos.configtree.ConfigTreeError: Path [b'interfaces bridge'] doesn't exist