tunnel: T3381: fix error when switching from mGRE to GRE mode
Linux does not support changing the remote address from any (multipoint
GRE as used by DMVPN) to a discrete remote address. THis will return an
error: add tunnel "tun1" failed: Invalid argument

This can be handled by detecting the mGRE -> GRE change and re-create the tunnel
silently.

(cherry picked from commit ea2a22f7844735021fb638c911527e612abfbc69)