T3357: Fix invoking TunnelIf() from op-mode
As we can also use the TunnelIf() class from op-mode we must ensure that read-only
access to the class works even if required configuration keys as "encapsulation"
are not passed to the class on invokation.

This fixes an isse where "show interfaces tunnel" returned:

Traceback (most recent call last):
  File "/usr/libexec/vyos/op_mode/show_interfaces.py", line 313, in <module>
    args.vrrp
  File "/usr/libexec/vyos/op_mode/show_interfaces.py", line 48, in handled_function
    function(*args, **kwargs)
  File "/usr/libexec/vyos/op_mode/show_interfaces.py", line 222, in run_show_intf_brief
    for interface in filtered_interfaces(ifnames, iftypes, vif, vrrp):
  File "/usr/libexec/vyos/op_mode/show_interfaces.py", line 77, in filtered_interfaces
    interface = klass(ifname, create=False, debug=False)
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/tunnel.py", line 99, in __init__
    if self.iftype in ['gretap', 'ip6gretap']:
AttributeError: 'TunnelIf' object has no attribute 'iftype'