dhcp: T4832: fix TypeError in smoketest
Commit cca7ec3e ("T4832: dhcp: Add IPv6-only dhcp option support (RFC 8925)")
extended the smoketests but used int over str when calilng the CLI wrapper.

This led to:
TypeError: sequence item 7: expected str instance, int found