ipv6: eui64: T3413: add custom validator
VyOS 1.2 (crux) rejected prefixes other then of site /64.
[ interfaces ethernet eth0 ipv6 address eui64 2006:ab00:abe1::2/127 ]
Error: Prefix lenght is 127.  It must be 64.

Same should be done on VyOS 1.3 and newer

(cherry picked from commit 6f6cd6552384704700f08e9367e167796b1f7fde)