isis: T6160: NameError: name 'process' is not defined
This is a leftover after commit 0e050cb35 (isis: T3417: drop artificial "domain"
node identifying the IS-IS process name). Drop all references to "process"
variable.

Specifying:

set protocols isis interface eth1
set protocols isis net '49.0001.1921.6825.5255.00'
set protocols isis redistribute ipv4 bgp

Triggered an exception

Traceback (most recent call last):
  File "/usr/libexec/vyos/conf_mode/protocols_isis.py", line 309, in <module>
    verify(c)
  File "/usr/libexec/vyos/conf_mode/protocols_isis.py", line 158, in verify
    f'"protocols isis {process} redistribute {afi} {proto}"!')
                       ^^^^^^^
NameError: name 'process' is not defined