powerctl: T2010: bugfix "TypeError: 'NoneType' object is not subscriptable"
Commit d6384b2 ("powerctl: T2010: report reboot time in current timezone")
added a migrator from UTC to local timezone but reading in the base value up
for conversion was done outside the proper if/else clause leading to a:
TypeError: 'NoneType' object is not subscriptable