container: T6208: fix AttributeError: 'ConfigDict' object has no attribute 'upper'
Commit b30faa43c (container: T6208: rename "cap-add" CLI node to "capability")
added an AttributeError referencing an out of scope variable.

This has been fixed.