lldp: T1896: bugfix SyntaxError: invalid syntax
Commit 66f8be0 ("lldp: T1896: remove MED civic based location information")
removed MED civic location support, but there was an error in an if/elif
statement. This has been fixes.

  File "/usr/libexec/vyos/conf_mode/lldp.py", line 191
    elif len(location['coordinate_based']) > 0:
       ^
  SyntaxError: invalid syntax