container: T6074: do not allow deleting images which have a container running
The current VyOS container image manipulation "delete container image" command
allows force removal of container images - even if they still have a container
running.

Drop the --force option from the op-mode script.

vyos@vyos:~$ delete container image 2636705a815a
Error: image used by 6adb0175d47f.. image is in use by a container: consider
listing external containers and force-removing image