isis: T3693: bugfix Jinja2 template
Commit 472c9568 ("isis: T3693: Adding IPv6 redistribution to ISIS") did not
pass rendering, am exception got thrown:

jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'protocol'

This commit fixes the templateing code.