bridge: T1783: bugfix removal of member interface
Fix error when deleting a member with:
  delete interfaces bridge br0 member interface eth1

  Traceback (most recent call last):
    File "/usr/libexec/vyos/conf_mode/interfaces-bridge.py", line 304, in <module>
      apply(c)
    File "/usr/libexec/vyos/conf_mode/interfaces-bridge.py", line 267, in apply
      br.del_port( intf['name'] )
  TypeError: string indices must be integers