T1277: [dhcpv6-server] bugfix 'show dhcpv6 server leases'
The script did not check if the service was actually configured or not.
This caused a FileNotFoundError for unconfigured services.

  vyos@vyos:~$ show dhcpv6 server leases
  Traceback (most recent call last):
    File "/usr/libexec/vyos/op_mode/show_dhcpv6.py", line 77, in <module>
      leases = get_leases(lease_file, state='active')
    File "/usr/libexec/vyos/op_mode/show_dhcpv6.py", line 46, in get_leases
      leases = IscDhcpLeases(lease_file).get()
    File "/usr/lib/python3/dist-packages/isc_dhcp_leases/iscdhcpleases.py", line 110, in get
      with open(self.filename) as lease_file:
  FileNotFoundError: [Errno 2] No such file or directory: '/config/dhcpdv6.leases'

(cherry picked from commit a6700c7d3b75854c3b213b65951a51464cd073be)