T5921: Fix OpenConnect verify for local users
Fix verify error for the VPN OpenConnect configuration with
local authentication and without any user

  File "/usr/libexec/vyos/conf_mode/vpn_openconnect.py", line 94, in verify
    if not ocserv["authentication"]["local_users"]:
KeyError: 'local_users'

(cherry picked from commit 71644dfed63f6248525db3c3bc9493c059707a2a)