vyos.ifconfig: T3883: bugfix VRF deletion
We can not pass None as VRF name, this raises an exception.

OSError: [Errno 255] failed to run command: ip link set dev eth2 master None

(cherry picked from commit e687502b1cf4a3e15c562a3662afcbe0776b1fe7)