Debian: containers: T2216: add missing dependency on uidmap
Fixes the following error:

vyos@vyos:~$ podman logs 2511d118563f
WARN[0000] The cgroupv2 manager is set to systemd but there is no systemd user session available
WARN[0000] For using systemd, you may need to login using an user session
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1002` (possibly as root)
WARN[0000] Falling back to --cgroup-manager=cgroupfs
Error: cannot find newuidmap: exec: "newuidmap": executable file not found in $PATH