ndppd: T2518: add missing if statement for translation address in Jinja2 template
This triggered a bug during smoketesting.

File "/usr/share/vyos/templates/proxy-ndp/ndppd.conf.tmpl", line 24, in top-level template code
  {%         if config.translation.address is defined and config.translation.address | is_ip_network  %}
File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 471, in getattr
  return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'translation'