wwan: T2529: fix validation logic for non existing devices
A non existing device usb0b1.4p1.?? device was not detected, as find_device_file()
returned None which can not be passed into os.path.exists().

Traceback (most recent call last):
  File "/usr/libexec/vyos/conf_mode/interfaces-wirelessmodem.py", line 126, in <module>
    verify(c)
  File "/usr/libexec/vyos/conf_mode/interfaces-wirelessmodem.py", line 60, in verify
    if dev_path is None or os.path.exists(find_device_file(dev_path)):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType