dns-forwarding: T2318: bugfix migration script
Commit bbea850ea5f ("ifconfig: T2057: remove need for interface-types.json")
called the Interface() class with a wrong input variable, this caused the
following error:

Traceback (most recent call last):
  File "/opt/vyatta/etc/config-migrate/migrate/dns-forwarding/1-to-2", line 64, in <module>
    raise ValueError(f'Invalid interface name {intf}')
ValueError: Invalid interface name eth0 vif 202