op-mode: dhcp: T2316: bugfix TypeError
Commit d4b1bc0b ("op-mode: dhcp/dhcpv6: T2268: prettify output for invalid
input") uses a different API which caused a TypeError.

TypeError: get_leases() missing 1 required positional argument: 'leases'