nat: T2199: bugfix dry-run newly generated config before install
Commit bb76e8d7f1635 ("nat: T2199: dry-run newly generated config before
install") added support to verify the generated nftables ruleset. Unfortunately
if the verify failed - a Python exception was triggered:

  NameError: name 'nftables_ct_file' is not defined

This was due to bad copy/pasting.