template: T2947: backport additional Jinja2 filters
is_ip_network and compare_netmask Jinja2 filter have been added via commit
920789798 ("nat: T2947: add many-many translation") on "current" and are
required for the 1:1 NAT functionality.

jinja2.exceptions.TemplateAssertionError: no filter named 'is_ip_network'