conntrack: T3275: bugfix XML generation
This commit fixes an error introduced by 43fcc0db0 ("conntrack: T3275: migrate
'disable' syntax to 'enable' syntax for the new default behavior") as the
<valueless/> option can only be used on leafNodes. THis triggered the following
build error:

ValueError: <valueless/> is only allowed in <leafNode>