T6026: QoS hide attempts to delete qdisc from devices
Hide unexpected output by attempts of deleting `qdisc` from
interfaces

[ qos ]
Error: Cannot find specified qdisc on specified device.
Error: Cannot delete qdisc with handle of zero.

(cherry picked from commit 6dcb68ba5553ac94eb3a9da4a915999500b00ab2)