vrf: T3655: fix potential error when removing VRF connection tracking table
This extends commit 22791e26 ("VRF: T3655: proper connection tracking for VRFs")
so that when the netfilter table is removed, we first check if it exists at all,
and if it does not exist we do not remove it.

This fixes the smoketest error:
PermissionError: [Errno 1] failed to run command: nft delete table inet vrf_zones