pppoe: bugfix template name after migration to ip-up scripts
Commit 6a0c6783d8b2 ("pppoe: migrate alias and vrf script from pre-up to up")
changed the name of the ip-up script template but the template definition has
been forgotten.

This caused:
  NameError: name 'config_pppoe_ip_up_tmpl' is not defined