smoketest: dhcpv6-relay: bugfix TypeError
Commit e28b10ce ("smoketest: dhcpv6-relay: use setUpClass() over setUp()")
introduced a TypeError:

   TypeError: cli_set() missing 1 required positional argument: 'config'

This has been fixed.