vxlan: T3867: add multicast validator for group address
The group CLI node takes a multicast IPv4 or IPv6 address - this must be input
validated to not case any OS exception

cpo@LR1.wue3# show interfaces vxlan
 vxlan vxlan0 {
+    group 254.0.0.1
     source-address 172.18.254.201
+    source-interface dum0
     vni 10
 }

Results in OSError beeing rasied with the following context:
  Error: argument "254.0.0.1" is wrong: invalid group address

(cherry picked from commit 0d7cd4ed5725d3e79faad5abc0801631c2ffc813)