conf_mode/interfaces-wireless.py: fix typos in wireless VLAN code
The typos cause the configurator to throw an exception when a wireless VLAN is specified:

Traceback (most recent call last):
  File "/usr/libexec/vyos/conf_mode/interfaces-wireless.py", line 1463, in <module>
    apply(c)
  File "/usr/libexec/vyos/conf_mode/interfaces-wireless.py", line 1433, in apply
    vlan = e.add_vlan(vif['id'])
NameError: name 'e' is not defined