T4911: op-mode: bugfix AttributeError: 'str' object has no attribute 'items'
One can not always ensure that "interface" is of type list, add safeguard.
E.G. Juniper Networks, Inc. ex2300-c-12t only has a dict, not a list of dicts

So this is actually an upstream lldpd bug where the output depends on the amount
of data transmitted.