vyos.configdict(): T4369: bugfix - execution order in leaf_node_changed()
Commit c685c0f7 ("vyos.configdict(): T4369: leaf_node_changed() must return True
when node is added") added a code path then a node was newly added to the CLI.
Unfortunately it turned out that this introduced a regression:

File "/usr/lib/python3/dist-packages/vyos/ifconfig/wireguard.py", line 230, in update
  super().update(config)
File "/usr/lib/python3/dist-packages/vyos/ifconfig/interface.py", line 1428, in update
  for addr in list_diff(config['address_old'], new_addr):
File "/usr/lib/python3/dist-packages/vyos/configdict.py", line 105, in list_diff
  return [item for item in first if item not in second]
TypeError: 'bool' object is not iterable

The execution order of the if statements is essential and the new check was
moved to the bottom to not interfere with the existing logic.

(cherry picked from commit 1a1094c28e32c3d6d072cf14a38aa631d51b8aee)