console: T2624: fix migration script for configured powersave and no console
When the 'powersave' option under 'system console' was defined but no actual
serial console device this cause the following error during migration:

Loading configuration from 'config.boot'
Traceback (most recent call last):
  File "/opt/vyatta/etc/config-migrate/migrate/system/16-to-17", line 45, in <module>
    for device in config.list_nodes(base + ['device']):
  File "/usr/lib/python3/dist-packages/vyos/configtree.py", line 236, in list_nodes
    raise ConfigTreeError("Path [{}] doesn't exist".format(path_str))
vyos.configtree.ConfigTreeError: Path [b'system console device'] doesn't exist