T560: bugfix access to NoneType object
Commit f1bbc20716 ("Add jinja2 and ipaddrcheck to dependencies.")
introduced access to a NoneType object when the service was removed.

This happened after:
 $ delete service dns forwarding
 $ commit

File "/opt/vyatta/sbin/vyos-config-dns-forwarding.py", line 201, in <module>
  verify(c)
File "/opt/vyatta/sbin/vyos-config-dns-forwarding.py", line 164, in verify
  if not dns['interfaces']:
TypeError: 'NoneType' object is not subscriptable